import streamlit as st
st.title("Registration")
first,last = st.columns(2)
first.text_input("Fist Name")
last.text_input("Last Name")
email,mob = st.columns([3,1])
email.text_input("Email ID")
mob.text_input("Mobile no.")
user,pw1,pw2 = st.columns(3)
user.text_input("User name")
pw1.text_input("Enter Password",type="password")
pw2.text_input("Retype your password", type="password")
ch,b1,sub = st.columns(3)
ch.checkbox("I agree")
sub.button("Submit")
